In [5]:
# import libraries

# Data Analysis Libraries
import pandas as pd 
import numpy as np

# Visualization Libraries
import matplotlib.pyplot as plt

# Machine Learning Libraries
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay
)

In [ ]:
# Load the dataset
try:
    df = pd.read_csv("day_04_student_performance_prediction_dataset.csv")
    print("Dataset loaded successfully.")
except FileNotFoundError:
    print("Error: The dataset file was not found. Please check the file path and try again.")

Dataset loaded successfully.

In [7]:
df.head()

,Student ID,Student Name,Age,Gender,Course,Attendance,Assignment Score,Midterm Score,Final Score,Result
0,S001,Ali,23,Male,Artificial Intelligence,51,87,70,61,1
1,S002,Fatima,19,Female,Data Science,97,46,46,84,1
2,S003,Bilal,18,Male,Artificial Intelligence,55,53,64,94,1
3,S004,Hina,22,Female,Artificial Intelligence,85,52,88,58,1
4,S005,Hamza,21,Male,Cyber Security,50,88,55,84,1

In [8]:
df.tail()

,Student ID,Student Name,Age,Gender,Course,Attendance,Assignment Score,Midterm Score,Final Score,Result
95,S096,Amna,21,Female,Software Engineering,60,87,95,87,1
96,S097,Farhan,20,Male,Data Science,90,57,97,60,1
97,S098,Komal,20,Female,Software Engineering,54,85,71,60,1
98,S099,Owais,20,Male,Cyber Security,70,97,45,47,0
99,S100,Nimra,19,Female,Data Science,74,84,54,57,1

In [9]:
df.sample(5)

,Student ID,Student Name,Age,Gender,Course,Attendance,Assignment Score,Midterm Score,Final Score,Result
39,S040,Nimra,23,Female,Software Engineering,72,67,87,89,1
84,S085,Hamza,23,Male,Software Engineering,93,87,57,68,1
79,S080,Nimra,21,Female,Data Science,66,42,90,30,0
48,S049,Imran,19,Male,Cyber Security,63,43,42,70,1
46,S047,Talha,19,Male,Software Engineering,50,64,68,88,1

In [11]:
df.shape

(100, 10)

In [12]:
df.columns

Index(['Student ID', 'Student Name', 'Age', 'Gender', 'Course', 'Attendance',
       'Assignment Score', 'Midterm Score', 'Final Score', 'Result'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student ID        100 non-null    str
 1   Student Name      100 non-null    str
 2   Age               100 non-null    int64
 3   Gender            100 non-null    str
 4   Course            100 non-null    str
 5   Attendance        100 non-null    int64
 6   Assignment Score  100 non-null    int64
 7   Midterm Score     100 non-null    int64
 8   Final Score       100 non-null    int64
 9   Result            100 non-null    int64
dtypes: int64(6), str(4)
memory usage: 7.9 KB

In [14]:
df.describe()

,Age,Attendance,Assignment Score,Midterm Score,Final Score,Result
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,21.190000,73.580000,68.740000,66.890000,64.490000,0.730000
std,1.993398,15.738507,17.134418,19.217992,19.804854,0.446196
min,18.000000,50.000000,40.000000,35.000000,30.000000,0.000000
25%,20.000000,58.750000,55.000000,50.750000,46.250000,0.000000
50%,21.000000,72.000000,67.000000,64.000000,61.000000,1.000000
75%,23.000000,88.250000,82.500000,86.000000,81.000000,1.000000
max,24.000000,100.000000,99.000000,100.000000,100.000000,1.000000

In [15]:
df.isnull().sum()

Student ID          0
Student Name        0
Age                 0
Gender              0
Course              0
Attendance          0
Assignment Score    0
Midterm Score       0
Final Score         0
Result              0
dtype: int64